version: "3.5"

services:
  web:
    image: webdevops/php-nginx:7.3
    working_dir: /app
    ports:
      - 8060:80
    depends_on:
      - database
    volumes:
      - .:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DATE_TIMEZONE: "Europe/Paris"
      PHP_DISPLAY_ERRORS: 1

  database:
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - "3307:3307"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 8061:80
    environment:
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: database
